server:
  http_listen_port: 7060
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: grafana
  static_configs:
  - targets:
      - grafana
    labels:
      job: grafana
      __path__: "C:/kafka-workspace/kafka-monitoring/grafana-8.0.6/data/log/grafana.log"

- job_name: liferay-node1
  static_configs:
  - targets:
      - liferay-node1
    labels:
      job: liferay-node1
      __path__: "C:/Liferay/Liferay74/liferay-ce-portal-7.4.1-ga2-node1/logs/*.log"
      
- job_name: liferay-node2
  static_configs:
  - targets:
      - liferay-node2
    labels:
      job: liferay-node2
      __path__: "C:/Liferay/Liferay74/liferay-ce-portal-7.4.1-ga2-node2/logs/*.log"